const fs = require("fs");
const path = require("path");
const exif = require("exif-parser");

const imageDir = path.join(__dirname, "pizza/images");
const pageFile = path.join(__dirname, "pizza/index.html");

function getImageDate(filePath) {
  try {
    const buffer = fs.readFileSync(filePath);
    const parser = exif.create(buffer);
    const result = parser.parse();

    if (result.tags && result.tags.DateTimeOriginal) {
      return result.tags.DateTimeOriginal * 1000; // convert to ms
    }
  } catch (e) {
    // ignore errors
  }

  // fallback: file modified time
  return fs.statSync(filePath).mtimeMs;
}

// read image files
let files = fs.readdirSync(imageDir).filter(file =>
  /\.(jpg|jpeg|png|webp)$/i.test(file)
);

// attach dates
files = files.map(file => {
  const fullPath = path.join(imageDir, file);
  return {
    name: file,
    date: getImageDate(fullPath)
  };
});

// sort newest → oldest
files.sort((a, b) => b.date - a.date);

// generate gallery
const gallery = files.map(file => {
  return `    <img src="/pizza/images/${file.name}" loading="lazy" alt="">`;
}).join("\n");

// read page
let page = fs.readFileSync(pageFile, "utf8");

// replace marker
page = page.replace(
  /<!-- IMAGES HERE -->/,
  gallery
);

// write back
fs.writeFileSync(pageFile, page);

console.log("Pizza gallery generated by EXIF date.");
